<?php

/**
 * @file
 * Contains wildlife_habitats_hierarchy.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_help().
 */
function wildlife_habitat_hierarchy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wildlife_habitats_hierarchy module.
    case 'help.page.wildlife_habitats_hierarchy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides blocks for sibling/children habitat relations.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function wildlife_habitat_hierarchy_entity_extra_field_info() {
  $extra_fields = [];

  // Add a Related Habitats extra field to Habitat nodes.
  $extra_fields['node']['habitat']['display']['related_habitats'] = [
    'label' => t('Related Habitats'),
    'description' => t('Children or siblings of the current habitat.'),
    'weight' => 0,
    'visible' => FALSE,
  ];

  return $extra_fields;
}

/**
 * Implements hook_entity_view().
 */
function wildlife_habitat_hierarchy_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // Only add the field if the current display contains the extra field.
  if (empty($display->getComponent('related_habitats'))) {
    return;
  }

  $habitat_relation_service = Drupal::service('wildlife_habitat_hierarchy.habitat_relations');
  $build['related_habitats'][] = $habitat_relation_service->getHabitatRelations($entity);
}
