<?php

/**
 * @file
 * Contains wildlife_google_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wildlife_google_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wildlife_google_api module.
    case 'help.page.wildlife_google_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Settings and default config for Google&#039;s API') . '</p>';
      return $output;

    default:
  }
}
