minimum_single: 20
minimum_multiple: 0
disable_search_threshold: 0
minimum_width: 250
jquery_selector: select
search_contains: false
disable_search: false
placeholder_text_multiple: 'Choose some options'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
disabled_themes:
  seven: '0'
  jackdaw: '0'
  wildlife_trust: '0'
  wildlife_trust_admin: '0'
chosen_include: 0
_core:
  default_config_hash: 8OBgqA1x01J7SgSvBzOELfxP9Bu998XgnQjf4EN40mo
