icon_base: 'public://media-icons/generic'
_core:
  default_config_hash: YMsgn0Y9ZO0Iu9iTMqqw6_Uev6-rVAdgxpJSy1s4-zc
dependencies:
  config:
    - media_entity.bundle.image
    - views.view.browser
    - views.view.media
