overview_left: 'my_drafts:my_awaiting'
overview_right: 'my_drafts:my_drafts'
overview_main: 'workbench_edited:block_1'
edits_main: 'workbench_edited:embed_1'
all_main: 'workbench_recent_content:embed_1'
_core:
  default_config_hash: aGR45_bxRagev3Ecuwgjvr3x2Ccgsmsk-Evv-SIkwQM
