/**
 * Sass Globbing setup.
 *
 * You must add each of the folders you want to be "globbed" using this file.
 *
 * Use the following filename format to keep globbing import files identifiable
 * (and ignored by .gitignore):
 *   __filename.scss
 *
 * Don't forget to add an @import for the generated file to a scss file:
 *   @import 'foldername/__filename';
 *
 */
module.exports = {
  dist: {
    files: {
      'sass/core/__core.scss': 'sass/core/**/*.scss',
      'sass/base/__base.scss': 'sass/base/**/*.scss',
      'sass/layouts/__layouts.scss': 'sass/layouts/**/*.scss',
      'sass/components/__components.scss': 'sass/components/**/*.scss'
    },
    options: {
      useSingleQuotes: false,
      signature: '// Generated by grunt-sass-globbing, do NOT edit manually.'
    }
  }
};
